[package]
name = "ludi-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.4"
proc-macro-error = "1.0"
darling = "0.20"
