[package]
name = "ludi-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["futures-mailbox"]
futures-mailbox = []

[dependencies]
futures-core = { version = "0.3" }
futures-util = { version = "0.3", features = ["sink"] }
futures-channel = { version = "0.3", features = ["sink"] }
